name: Go Test Validation

on:
  pull_request:
    branches:
      - release/*

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Run Go tests
        run: |
          go test ./...
        env:
          CGO_ENABLED: 0
